
## Path to RNA-seq sample samplesheet
samplesheet: 'samplesheet.csv'

## Path to to imputed genotyping vcf
vcf: '/proj/phanstiel_lab/Data/processed/CQTL/geno/CQTL_COA_01_GDA8_COA2_01_COA3_01_GDA8_COA4_COA5/vcf/CQTL_COA_01_GDA8_COA2_01_COA3_01_GDA8_COA4_COA5_ALL_qc.vcf.gz'

chromNames: '../../chromNames_hg38.txt' # 2-column text file. 1st column: format of chromosome names in vcf file, 2nd column: required format of chromosome names for compatibility with contigs

# GRCh38
genomeDir: '/proj/seq/data/STAR_genomes/GRCh38_p10_GENCODE' # Path to folder of STAR genome.
chromSizes: '/proj/seq/data/STAR_genomes/GRCh38_p10_GENCODE/chrNameLength.txt' # Path to file of chromosome names and lengths.
sequence: '/proj/phanstiel_lab/References/genomes/GENCODE.GRCh38.p10/Sequence/GRCh38.p10.genome.fa.gz' # Path to reference sequence gzipped fasta file. The associated sequence dictionary must be in the same directory as this file.

## Minimum number of total read counts from both alleles to consider a heterozygote from RNA
# Hollander et al used 25
minTotalAlleleCounts: 10
## Minimum number of read counts from either allele to consider a heterozygote from RNA
# Hollander et al used 10
minAlleleCounts: 2
