__default__:
  name: "{rule}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 16G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{jobid}.err"
