
## Path to genotyping data samplesheet
geno: 'geno.csv'

## Genome-specific reference parameters
# Path to population reference data (in PLINK binary format, all autosomes merged)
ref: '/proj/phanstiel_lab/SHARE/genomes/1000G/GRCh37/1000G_phase3_chrALL_biallelic'
# Path to panel file of above population reference data
panel: '/proj/phanstiel_lab/SHARE/genomes/1000G/GRCh37/1000G_phase3.panel'
# Path to reference sequence fasta
sequence: '/proj/phanstiel_lab/SHARE/genomes/hg19/Sequence/hg19.fa'

## Name of data 'population'
pop_name: 'chQTL'

## Path to imputed genotyping data samplesheet
vcf: 'vcf.csv'