
## Path to RNA-seq sample samplesheet
samplesheet: 'samplesheet.csv'

## Path to vcf processed with VCFproc in first workflow
vcf: '/pine/scr/n/e/nekramer/6_16_22_AIproc/AIpipe/AIpipe/output/vcf/CQTL_COA_01_GDA8_COA2_01_COA3_01_GDA8_COA4_COA5_nodups_biallelic.vcf.gz'

## Minimum number of total read counts from both alleles to consider a heterozygote from RNA
minTotalAlleleCounts: 10
## Minimum number of read counts from either allele to consider a heterozygote from RNA
minAlleleCounts: 2
## Threshold of number of heterozygotes a variant must have to remain in the analysis
minHets: 5
## Weight value for homozygotes in weight matrix for differential analysis
weightVal: 1e-6

## Path to dbSNP VCF file
dbsnp: '/proj/phanstiel_lab/References/genomes/GENCODE.GRCh38.p13/dbSNP/dbSNP155.GRCh38.p13.vcf.gz'