## Samplesheets
samplesheet: 'samplesheet.csv' # RNA
donorSamplesheet: 'donorSamplesheet.csv' # donor information
dnaSamplesheet: 'dnaSamplesheet.csv' # DNA

## Path to processed sample alignments, normalized qunts
data: '/proj/phanstiel_lab/Data/processed/CQTL/rna/freeze_11_22_2022'

## Path to vcf inputted to QTL mapping
vcf: '/pine/scr/n/e/nekramer/iteratePEER_RNAKitBatch_DNAKitBatch/output/vcf/CQTL_COA_01_GDA8_COA2_01_COA3_01_GDA8_COA4_COA5_COA6_COA7_renameChroms.vcf.gz'

## Path to directory of PEER factors and number of PEER factors to calculate correlations with
peer: '/pine/scr/n/e/nekramer/iteratePEER_RNAKitBatch/output/covar'
Nk: 10

sequence: '/proj/phanstiel_lab/References/genomes/GENCODE.GRCh38.p13/Sequence/GRCh38.p13.genome.fa.gz'

## Path to permutation pass eGenes with FDR calculations
eGenes: '/pine/scr/n/e/nekramer/iteratePEER_RNAKitBatch/output/qtl'

## Path to GTEx data
gtex_egene: '/proj/phanstiel_lab/External/consortium/gtex/eqtls/egenes/'
gtex_signif: '/proj/phanstiel_lab/External/consortium/gtex/eqtls/signif/'

## FDR threshold
FDRthreshold: 0.05

## Software versions
QTLToolsVersion: "1.3.1"
Rversion: "4.1.3"
gatkVersion: "4.2.5.0"
picardVersion: "2.26.11"
samtoolsVersion: "1.9"
pythonVersion: "3.9.6"
