#!/usr/bin/env python3

import pandas as pd
import os

## Load config file
configfile: "config/config.yaml"

## Read in samplesheet
genos = pd.read_csv(config["geno"], sep = ",")

## Convert samplesheet columns to strings
genos = genos.astype(str)

## Read in samplesheet with imputed vcfs
vcfs = pd.read_csv(config["vcf"],sep=",")

## Convert samplesheet columns to strings
vcfs = vcfs.astype(str)

## Grab vcf paths for all chromosomes
vcfs = vcfs['vcf_path']

mergeName = '_'.join(genos['Batch'])

## Define actions on success
onsuccess:

    ## Success message
    print("Imputed VCFs qc'd succesfully! Use these vcfs in the Allelic Imbalance pipeline or QTL Mapping pipeline.")

rule all:
    input: 
        'output/vcf/' + mergeName + '_ALL_qc.vcf.gz'

rule concatVCF:
    input: 
        vcfs
    output:
        temp('output/vcf/' + mergeName + '_ALL.vcf.gz')
    params:
        prefix = mergeName
    log:
        err1 = "output/vcf/logs/concatVCF.err"
    shell:
        """
        mkdir -p output/vcf/logs
        module load samtools
        bcftools concat -o output/vcf/{params.prefix}_ALL.vcf {input} 2> {log.err1}
        bgzip output/vcf/{params.prefix}_ALL.vcf
        """      

rule qcVCF:
    input:
        'output/vcf/' + mergeName + '_ALL.vcf.gz'
    output:
        'output/vcf/' + mergeName + '_ALL_qc.vcf.gz'
    params:
        prefix = mergeName,
        geno = config['miss_call'],
        hwe = config['hwe'],
        maf = config['maf']
    log:
        out = "output/vcf/logs/" + mergeName + "_ALL_qc.out"
    shell:
        """
        mkdir -p output/vcf/logs
        module load plink
        plink --vcf {input} --const-fid 0 --geno {params.geno} --hwe {params.hwe} --maf {params.maf} --recode vcf --out output/vcf/{params.prefix}_ALL_qc 1> {log.out}
        mv output/vcf/{params.prefix}_ALL_qc.log output/vcf/logs/{params.prefix}_ALL_qc.err
        rm output/vcf/{params.prefix}_ALL_qc.nosex

        module load samtools
        bgzip output/vcf/{params.prefix}_ALL_qc.vcf
        """