name: googleSheet
on:
  push:
    paths:
      - 'scripts/sampleParsing.R'


jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.1'

      - name: Install packages
        run: Rscript -e "install.packages(c('googlesheets4', 'tidyverse'))"

      - name: Execute sample parsing script
        env:
            GOOGLE_SHEET: ${{ secrets.GOOGLE_SHEET }}
            GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
            GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        run: Rscript scripts/sampleParsing.R